---
title: "2024-12-02_pseudowords_sampling"
author: "Camille Charrier"
date: "2024-12-02"
output:
  html_document:
    df_print: paged
    toc: true
    theme: lumen
    toc_float: true
    number_sections: true
    highlight: tango
    fig_caption: true
    code_folding: hide
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE,fig.align="center") 
options(encoding = 'UTF-8')
```

# - Abstract

Calibration of feedforward ratio



# - Pretreatments

## - Import

Load of packages needed for the further computations

```{r}
library(dplyr)
library(ggplot2)
library(stringr)
library(tidyr)
library(colorspace)
```


## - Global variables

Load of the global variables needed for the import of databases and the plots

```{r}
path_flp_pw = "C:/Users/Camille/Documents/LPNC/_Thesis/Studies/T1_ClassicalEffects/Reading/PW/flp_pseudowords.csv"


cbp <- c("#FFB23D", "#38A29A", "#19609E", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

cbp2 <- c("#FFB23D", "#18578E", "#35C3B8", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")

```


## - Load data

Load the databases into dataframe variables

```{r}
data = read.csv2(path_flp_pw)
```

# - Decription

```{r}
data %>% group_by(len) %>% summarise(n=n())

data %>% ggplot(aes(x=as.factor(len),y=err)) +
  geom_boxplot() +
  theme_classic(12)
```

# - Sampling

```{r}
data %>% filter(err==0 & nused!=2 & len>2 & len<9) %>% group_by(len) %>% sample_n(50,replace=FALSE) %>%  write.csv("01_pw_flp_50bylen.csv",row.names = FALSE)
```

